[package]
name = "repay"
version = "1.0.0"
authors = ["Alex Sayers <alex.sayers@gmail.com>"]

[dependencies]
bitset64 = { path = "bitset64" }
clap = "2.30"
env_logger = "0.5"
log = "0.4"
mcmf = "1.1"
mzsp = { path = "mzsp" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
